apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: iam-eltayeb-online-certificate
  namespace: iam-service
spec:
  secretName: iam-eltayeb-online-tls
  issuerRef:
    name: letsencrypt-prod-dns01
    kind: ClusterIssuer
  dnsNames:
  - "*.eltayeb.online"
