apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: iam-service-monitor
  labels:
    app: iam-service
    release: kube-prom-stack
spec:
  selector:
    matchLabels:
      app: iam-service
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
  namespaceSelector:
    matchNames:
    - iam-service
