apiVersion: v2
name: log-collector
description: A wrapper chart to deploy Promtail for my existing Loki
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: promtail
    version: "6.17.1"
    repository: "https://grafana.github.io/helm-charts"