apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-api-key-external-secret
  namespace: cert-manager
spec:
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: cloudflare-api-key-secret
    creationPolicy: Owner
  data:
  - secretKey: api-key
    remoteRef:
      key: CF-API-KEY
