apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-store
spec:
  provider:
    gcpsm:
      projectID: thmanyah-assessment
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcp-sa-key
            key: secret-key.json